### PR TITLE
SEO-2750 - AngularJS image alt text 

### PR DESCRIPTION
**Pull request by Sharly-Atieno**
|Title|Description|
|:--|:--|
|**Task Category** | Need to rename 4 image alt text|
|**Content task link/ Mail screenshot** | N/A |
|**Hotfix PR link** | https://github.com/syncfusion-content/angularjs-docs/pull/170
|**Ticket link/Task link** |https://syncfusion.atlassian.net/browse/SEO-2750 |
|**Excel/SharePoint link** | N/A |

### CODE REVIEW

**Comment by Sharly-Atieno** [comment]
rebuild

**Comment by Sharly-Atieno** [comment]
rebuild

**Comment by Sharly-Atieno** [comment]
rebuild

**Comment by Sharly-Atieno** [comment]
rebuild

**Comment by Sharly-Atieno** [comment]
rebuild

**Review by Aishwarya-Ganesan — APPROVED** [review]
Changes are fine.

**Pull request merged**
